# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
do_mv <- function(m, v) {
    .Call(`_panelGMM_do_mv`, m, v)
}

#' @export
do_ZuuZ <- function(Z, e, n, t) {
    .Call(`_panelGMM_do_ZuuZ`, Z, e, n, t)
}

#' @export
do_Zu <- function(Z, e, n, t) {
    .Call(`_panelGMM_do_Zu`, Z, e, n, t)
}

